# Generated by Django 4.2.4 on 2023-10-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='proNome',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='estoque',
            name='quanEsto',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
