# Generated by Django 4.2.4 on 2023-10-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_remove_funci_idfunci_funci_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funci',
            name='id',
        ),
        migrations.AlterField(
            model_name='funci',
            name='email',
            field=models.EmailField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
