# Generated by Django 4.2.4 on 2023-11-07 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_remove_funci_id_alter_funci_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='funci',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao.funci'),
        ),
    ]
