# Generated by Django 4.2.4 on 2023-11-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0005_estoque_funci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funci',
            name='email',
            field=models.EmailField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
